import React, { useMemo } from 'react';
import { useAppStore } from '@/store/useAppStore';
import { clsx } from 'clsx';

// Helper to format numbers with rounding
const formatNum = (num: number | undefined | null) => {
  if (num === undefined || num === null || num === 0) return "-";
  return num.toLocaleString(undefined, { minimumFractionDigits: 1, maximumFractionDigits: 1 });
};

// Helper for quantity formatting
const formatQty = (qty: number | undefined | null) => {
  if (qty === undefined || qty === null || qty === 0) return "-";
  return qty.toLocaleString();
};

export default function PrintableReport() {
  const { floors } = useAppStore();

  // 1. Filter and Sort Floors: B1 -> 1F -> 2F ... -> 7F
  const targetFloors = useMemo(() => {
    return floors.filter(f => {
      const name = f.name.toUpperCase().trim();
      // Only B1 and 1F~7F
      if (name === 'B1') return true;
      const numMatch = name.match(/^(\d+)F$/);
      if (numMatch) {
         const num = parseInt(numMatch[1]);
         return num >= 1 && num <= 7;
      }
      return false;
    }).sort((a, b) => {
      const getVal = (n: string) => {
        if (n.startsWith('B')) return -parseInt(n.substring(1));
        return parseInt(n.replace('F', ''));
      };
      return getVal(a.name) - getVal(b.name);
    });
  }, [floors]);

  if (targetFloors.length === 0) return null;

  return (
    <div className="bg-white text-slate-900 printable-container font-['Pretendard','Inter',sans-serif]">
      <style>{`
        @page {
          size: A4 landscape;
          margin: 12mm 10mm;
        }
        @media print {
          body {
            background: white !important;
            print-color-adjust: exact;
            -webkit-print-color-adjust: exact;
            margin: 0;
            padding: 0;
          }
           @page {
              /* Remove header/footers generated by some browsers to be safe, though users can toggle */
           }
          .page-break {
            page-break-before: always;
          }
          .printable-container {
             width: 100%;
             max-width: none;
             padding: 0;
             margin: 0;
          }
          thead {
            display: table-header-group;
          }
          tfoot {
            display: table-footer-group;
          }
          tr {
            page-break-inside: avoid;
          }
          td, th {
            page-break-inside: avoid;
          }
          .floor-section {
             margin-bottom: 0; 
          }
        }
        .empty-hatch {
          background-image: repeating-linear-gradient(45deg, #f1f5f9 0, #f1f5f9 2px, transparent 2px, transparent 8px);
        }
      `}</style>
      
      {/* Fixed Footer for all printed pages */}
      <div className="print-footer fixed bottom-0 left-0 right-0 hidden print:flex justify-between text-[11px] font-medium text-slate-500 pb-2 bg-white">
        <div>경상남도청 | 해안건축</div>
        <div>{/* Browser native page numbers will usually print bottom right */}</div>
      </div>

      {targetFloors.map((floor, idx) => (
        <div key={floor.id} className={clsx("floor-section", idx > 0 && "page-break")}>
          <FloorTable floor={floor} />
        </div>
      ))}
    </div>
  );
}

function FloorTable({ floor }: { floor: any }) {
  const { rooms, departments, stages, values, comparison, divisions } = useAppStore();

  const baseId = comparison.baseId || stages[0]?.id;
  const targetId = comparison.targetId || stages[stages.length - 1]?.id;

  // Filter rooms for this floor
  const floorRooms = useMemo(() => {
    return rooms.filter(r => r.floorId === floor.id).sort((a, b) => {
      const dA = departments.find(d => d.id === a.departmentId)?.order || 999;
      const dB = departments.find(d => d.id === b.departmentId)?.order || 999;
      if (dA !== dB) return dA - dB;
      return a.no.localeCompare(b.no, undefined, { numeric: true });
    });
  }, [rooms, floor.id, departments]);

  // Map values for faster access
  const valsMap = useMemo(() => {
    const map = new Map<string, any>();
    values.forEach(v => map.set(`${v.roomId}|${v.stageId}`, v));
    return map;
  }, [values]);

  // Group by department for summary rows
  const groupedRows = useMemo(() => {
    const result: any[] = [];
    let currentDeptId: string | null = null;
    let deptRooms: any[] = [];

    const addSummary = (dId: string, roomsOfDept: any[]) => {
      const dept = departments.find(d => d.id === dId);
      const div = divisions.find(v => v.id === dept?.divisionId);
      
      const summary: any = {
        id: `summary-${dId}`,
        isSummary: true,
        deptName: dept?.name || "기타",
        deptColor: div?.color || "#64748b",
        variant: 0
      };

      stages.forEach(s => {
        let total = 0;
        roomsOfDept.forEach(r => {
          const v = valsMap.get(`${r.id}|${s.id}`);
          if (v) total += (v.unitArea || 0) * (v.quantity || 0);
        });
        summary[`${s.id}_total`] = total;
      });
      
      if (baseId && targetId) {
        summary.variance = (summary[`${targetId}_total`] || 0) - (summary[`${baseId}_total`] || 0);
      }

      result.push(summary);
    };

    floorRooms.forEach(room => {
      if (room.departmentId !== currentDeptId) {
        if (currentDeptId !== null) {
          addSummary(currentDeptId, deptRooms);
        }
        currentDeptId = room.departmentId;
        deptRooms = [];
        
        // Add Department Header
        const dept = departments.find(d => d.id === currentDeptId);
        const div = divisions.find(v => v.id === dept?.divisionId);
        result.push({
          id: `header-${currentDeptId}`,
          isHeader: true,
          deptName: dept?.name || "기타",
          deptColor: div?.color || "#6366f1"
        });
      }
      deptRooms.push(room);
      
      const row: any = { ...room };
      stages.forEach(s => {
        const v = valsMap.get(`${room.id}|${s.id}`);
        row[`${s.id}_unit`] = v?.unitArea || 0;
        row[`${s.id}_qty`] = v?.quantity || 0;
        row[`${s.id}_total`] = (v?.unitArea || 0) * (v?.quantity || 0);
        row[`${s.id}_isEmpty`] = !v;
      });

      if (baseId && targetId) {
        row.variance = (row[`${targetId}_total`] || 0) - (row[`${baseId}_total`] || 0);
      }
      
      result.push(row);
    });

    if (currentDeptId !== null) {
      addSummary(currentDeptId, deptRooms);
    }

    return result;
  }, [floorRooms, departments, divisions, stages, valsMap, baseId, targetId]);

  const totalCols = 3 + stages.length * 3;

  return (
    <div className="w-full">
      <table className="w-full border-separate border-spacing-0 table-fixed text-[11px] print:text-[10px]">
        <thead>
          {/* Header Row mapped inside table to repeat on each page */}
          <tr>
             <td colSpan={totalCols} className="border-0 p-0 pb-4">
                <div className="flex items-end justify-between border-b-2 border-slate-950 pb-2">
                  <div>
                    <h2 className="text-xl font-bold tracking-tight text-slate-950">
                      {floor.name.startsWith('B') ? `지하 ${floor.name.substring(1)}층` : `지상 ${floor.name.replace('F', '')}층`} 세부 면적계획
                    </h2>
                    <div className="text-[10px] text-slate-500 font-medium mt-1">경상남도 서부의료원 건립사업 기본설계</div>
                  </div>
                  <div className="text-right">
                    <span className="text-[10px] font-bold text-indigo-600 bg-indigo-50 px-2 py-0.5 rounded border border-indigo-100 uppercase tracking-widest">
                      Detail Floor Report
                    </span>
                  </div>
                </div>
             </td>
          </tr>
          <tr>
            <th className="bg-[#E2E8F0] border-y border-r border-l border-[#CBD5E1] py-2 px-1 w-8 text-center font-bold text-[#334155]" rowSpan={2}>NO</th>
            <th className="bg-[#E2E8F0] border-y border-r border-[#CBD5E1] py-2 px-2 text-left w-24 sm:w-32 font-bold text-[#334155]" rowSpan={2}>실 명칭</th>
            {stages.map(s => (
              <th key={s.id} className="bg-[#E2E8F0] border-y border-r border-[#CBD5E1] py-2 px-1 text-center font-bold text-[#334155]" colSpan={3}>
                {s.name}
              </th>
            ))}
            <th className="bg-[#E2E8F0] border-y border-r border-[#CBD5E1] py-2 px-1 text-center w-16 font-bold text-[#334155]" rowSpan={2}>증감</th>
          </tr>
          <tr>
            {stages.map(s => (
              <React.Fragment key={`${s.id}-sub`}>
                <th className="bg-[#E2E8F0] border-b border-r border-[#CBD5E1] py-1 px-1 text-center font-medium text-slate-500 w-10">Net</th>
                <th className="bg-[#E2E8F0] border-b border-r border-[#CBD5E1] py-1 px-1 text-center font-medium text-slate-500 w-8">Qty</th>
                <th className="bg-[#E2E8F0] border-b border-r border-[#CBD5E1] py-1 px-1 text-center font-bold text-slate-900 w-12">Total</th>
              </React.Fragment>
            ))}
          </tr>
        </thead>
        <tbody className="bg-white">
          {groupedRows.map(row => {
            if (row.isHeader) {
               return (
                 <tr key={row.id} className="bg-slate-100/30">
                   <td colSpan={totalCols} className="border-b border-l border-r border-slate-300 py-1.5 px-4 font-bold text-slate-900">
                     <div className="flex items-center gap-2">
                       <div className="w-[4px] h-[12px] rounded-full" style={{ backgroundColor: row.deptColor }}></div>
                       {row.deptName}
                     </div>
                   </td>
                 </tr>
               );
            }
            if (row.isSummary) {
              return (
                <tr key={row.id} className="bg-slate-50 font-bold">
                  <td className="border-b border-l border-slate-300 py-1.5 px-1 text-center text-slate-400">-</td>
                  <td className="border-b border-l border-r border-slate-300 py-1.5 px-2 text-left text-slate-800">[{row.deptName} 소계]</td>
                  {stages.map(s => (
                    <React.Fragment key={s.id}>
                      <td className="border-b border-r border-slate-300 py-1.5 px-1 text-right text-slate-400">-</td>
                      <td className="border-b border-r border-slate-300 py-1.5 px-1 text-center text-slate-400">-</td>
                      <td className="border-b border-r border-slate-300 py-1.5 px-1 text-right text-indigo-900 font-inter font-bold bg-indigo-50">
                        {formatNum(row[`${s.id}_total`])}
                      </td>
                    </React.Fragment>
                  ))}
                  <td className={clsx(
                    "border-b border-r border-slate-300 py-1.5 px-1 font-inter text-[12px] font-bold text-right",
                    row.variance > 0 ? "text-blue-600" : row.variance < 0 ? "text-red-500" : "text-slate-400"
                  )}>
                    {row.variance > 0 ? "+" : ""}{formatNum(row.variance)}
                  </td>
                </tr>
              );
            }

            return (
              <tr key={row.id}>
                <td className="border-b border-l border-slate-300 py-1.5 px-1 text-center text-slate-400 font-mono text-[10px]">{row.no}</td>
                <td className="border-b border-l border-r border-slate-300 py-1.5 px-2 text-left font-medium text-slate-800 leading-tight">
                  {row.name}
                </td>
                {stages.map(s => {
                  const isEmpty = row[`${s.id}_isEmpty`];
                  return (
                    <React.Fragment key={s.id}>
                      <td className={clsx("border-b border-r border-slate-300 py-1.5 px-1 text-right font-inter text-slate-500", isEmpty && "empty-hatch")}>
                         {isEmpty ? "" : formatNum(row[`${s.id}_unit`])}
                      </td>
                      <td className={clsx("border-b border-r border-slate-300 py-1.5 px-1 text-center font-inter text-slate-500", isEmpty && "empty-hatch")}>
                         {isEmpty ? "" : formatQty(row[`${s.id}_qty`])}
                      </td>
                      <td className={clsx("border-b border-r border-slate-300 py-1.5 px-1 text-right font-inter font-bold text-slate-900 bg-slate-50/20", isEmpty && "empty-hatch")}>
                         {isEmpty ? "" : formatNum(row[`${s.id}_total`])}
                      </td>
                    </React.Fragment>
                  );
                })}
                <td className={clsx(
                  "border-b border-r border-slate-300 py-1.5 px-1 text-right font-inter text-[12px] font-bold",
                  row.variance > 0 ? "text-blue-600" : row.variance < 0 ? "text-red-500" : "text-slate-400"
                )}>
                  {row.variance === 0 ? "-" : (row.variance > 0 ? "+" : "") + formatNum(row.variance)}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

